name: base
dependencies:
- conda-forge::cudatoolkit=11.3.1
- numpy=1.21.2
- pillow=8.4.0
- pip=21.2.4
- python=3.9.7
- pytorch::pytorch=1.10.2=py3.9_cuda11.3_cudnn8.2.0_0
- scipy=1.7.3
- pytorch::torchvision=0.11.3=py39_cu113
- ffmpeg=4.2.2
- tqdm=4.62.3
