name: base
channels:
- conda-forge
- nvidia
- nodefaults
dependencies:
- mamba=1.3.1
- pip=23.0.1
- python=3.10.9
- pytorch::pytorch=2.0.0
- pytorch::pytorch-cuda=11.8
- scipy=1.10.1
- pytorch::torchvision=0.15.0
- tqdm=4.65.0
